import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/main/header";
import Footer from "@/app/components/main/footer";



export const metadata: Metadata = {
  title: "Pet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header />
        </header>

        <main>
        {children}
        </main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
