import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/main/header";
import Footer from "@/components/main/footer";



export const metadata: Metadata = {
  title: "Pet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full">
      <div className="mx-32">
        <header>
          <Header/>
        </header>

        <main className="border border-black">
          {children}
        </main>

        <footer>
          <Footer/>
        </footer>
      </div>
      </body>
    </html>
  );
}
